# Generated by Django 4.0 on 2022-02-03 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('url_id', models.CharField(auto_created=True, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('original_url', models.CharField(max_length=10000)),
                ('hashed_url', models.CharField(max_length=100)),
                ('validation_period', models.IntegerField(default=3)),
                ('creation_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
