# Generated by Django 3.2.9 on 2022-02-03 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='creation_date',
            field=models.DateField(),
        ),
    ]
