# Generated by Django 3.2.9 on 2022-02-03 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_api', '0002_alter_url_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='creation_date',
            field=models.DateTimeField(),
        ),
    ]
