# Generated by Django 3.2.9 on 2022-02-03 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_api', '0004_alter_url_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='creation_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
