# Generated by Django 3.2.9 on 2022-02-03 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_api', '0005_alter_url_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='valid',
            field=models.BooleanField(default=False, verbose_name=False),
            preserve_default=False,
        ),
    ]
