# Generated by Django 3.2.9 on 2022-02-03 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_api', '0006_url_valid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='valid',
            field=models.BooleanField(verbose_name=True),
        ),
    ]
