# Generated by Django 3.2.9 on 2022-02-07 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_api', '0007_alter_url_valid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='url_id',
        ),
        migrations.AlterField(
            model_name='url',
            name='hashed_url',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
